openapi: 3.0.0
info:
  title: CBDC數位貨幣測試API系統
  description: 資訊安全實驗室銀行端API
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8081
    description: 銀行伺服器
tags:
  - name: "登入"
    description: "從銀行領錢的API。"

paths:
  /api/login:
    post:
      tags:
      - "登入"
      summary: 登入使用者取得token。
      description: ""
      requestBody:
        description: 登入使用者取得token。
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              # 請求參數
              properties:
                account:
                  type: string
                  default: user
                  required: true
                password:
                  type: string
                  default: user 
                  required: true    
      responses:
        200:
          description: 收到回傳訊息。
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: int
                    example: 1
                  message:
                    type: string
                    example: Login success.
                  token:
                    type: string
                    example: 95f585c748524b1ba154c13a37f973f4

  # 驗證登入API
  /api/check_login:
    get:
      security:
        - token: []
      tags:
      - "登入"
      summary: 檢查使用者token
      description: ""
      # 請求參數
      parameters:
        - name: token
          in: query
          description: 檢查使用者token
          # required: true
          schema:
            type: string
      # 回應參數
      responses:
        '200':    # status code
          description: 顯示token是否有效。
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: int
                    example: 1
                  message:
                    type: string
                    example: Login success.
                  token:
                    type: string
                    example: 95f585c748524b1ba154c13a37f973f4

# 登出
  /api/logout:
    post:
      tags:
      - "登出"
      summary: 登出。
      description: ""
      requestBody:
        description: 登入使用者取得token。
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              # 請求參數
              properties:
                token:
                  type: string
                  required: true
      responses:
        200:
          description: 收到回傳訊息。
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: int
                    example: 1
                  message:
                    type: string
                    example: Login success.
                  token:
                    type: string
                    example: 95f585c748524b1ba154c13a37f973f4